version: '3.8'
services:
  web-api:
    build: .
    ports:
      - 8000:5000
  psql-db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - psql-db:/var/lib/postgresql/data

volumes:
  psql-db:
    driver: local