version: '3.8'
services:
  web-api:
    build: .
    ports:
      - 8000:5000
    depends_on:
      - psql-db
  psql-db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - psql-db:/var/lib/postgresql/data

volumes:
  psql-db: